export enum ConfigKeys {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',

  SMTP_FROM_EMAIL = 'SMTP_FROM_EMAIL',
  SMTP_HOST = 'SMTP_HOST',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_USER = 'SMTP_USER',
  SMTP_PASSWORD = 'SMTP_PASSWORD',
  SMTP_NAME = 'SMTP_NAME',
  SMTP_FROM_NAME = 'SMTP_FROM_NAME',

  API_KEY = 'API_KEY',
}
